.bumpversion.cfg
.github/workflows/build-and-publish.yml
LICENSE
README.md
watcher/argo.py
watcher/models.py
watcher/state.py
watcher/web.py

- The necessity to keep a connection to this app is no longer needed
- When a new task is added, the task ID is returned
- An additional endpoint is added that accepts task ID and returns its current status
- An additional endpoint is added to get the list of existing tasks (prep for UI integration)

feat: app logic change

---

.gitignore
Dockerfile
db/migrations/20220321190620_init.sql
docker-compose.yaml
poetry.lock
pyproject.toml
watcher/argo.py
watcher/settings.py
watcher/state.py
watcher/web.py

This PR introduces the following changes:
- Add support for storing state in PostgreSQL
- Docker image migrated from Alpine to Debian
- /api/v1/tasks accept mandatory timeframe parameters to limit output. Example: curl http://localhost:8080/api/v1/tasks?timestamp=1648055141
- dbmate is packaged into the docker image and an initial migration script is added

feat: add support for storing state in postgresql

---

cmd/argo-watcher/main.go
internal/models/task.go
web/src/App.js
web/src/Components/TaskView.js
web/src/Components/TasksTable.js
web/src/Services/Data.js

1. Created "Task details" page that can show all task info + have a unique link for the task
2. Improved task status details are shown in tables (not much improvement, but still)
The reasoning behind the changes is to make it easier to find task errors and get information on them

feat(frontend): add task details page

---

go.mod
web/src/App.js
web/src/Components/HistoryTasks.js
web/src/Components/RecentTasks.js
web/src/Components/TaskView.js
web/src/Components/TasksTable.js
web/src/index.css

Pull requests for #123 
* Created a dropdown for pagination, which is saved on refresh or event browser tab reopen (used local storage)
* Improved styling a bit, so that with default ten items per page the table fits the screen without scroll
* Reworked how item errors work. Instead of a popup they will appear in a separate row in the table now

feat(ui): items per page and minor improvements

---

cmd/argo-watcher/argo_api_test.go
cmd/argo-watcher/config/config_test.go

Adds unit tests for:
1. Config
2. argo api

chore: increase test coverage

---

cmd/argo-watcher/argo_status_updater.go
cmd/argo-watcher/argo_status_updater_test.go
cmd/argo-watcher/main.go
cmd/argo-watcher/router.go
cmd/argo-watcher/server.go
docs/development.md
internal/models/constants.go

created argo status updater tests + minor improvements to docs

chore: argo status updater tests

---

.goreleaser.yaml
web/src/Components/Navbar.js

The following changes were introduced:
- Removed `goreleaser` snapshot name override to produce a more reasonable versions value
- Adjusted frontend Github link generation to match version value generated by `goreleaser`
- Added latest built docker image tag to release footer

chore(goreleaser): automation adjustments

---

cmd/argo-watcher/argo.go
cmd/argo-watcher/argo_status_updater.go
cmd/argo-watcher/argo_status_updater_test.go
internal/models/argo.go
internal/models/argo_test.go
internal/models/task.go
internal/models/task_test.go

We talked about simplifying this class, since it's too bulky and non-trivial.
This PR is an attempt to make it more straight forward.
Notable changes:
1. Instead of fetching application extra time, we now re-use last application object we fetched
2. We don't do retries anymore in cases when application is not found
3. Error messages are standardized, with application deployment status in logs and reasons

chore: argo status updater changes

---

cmd/argo-watcher/config/config.go
cmd/argo-watcher/state/in_memory_state.go
cmd/argo-watcher/state/in_memory_state_test.go
cmd/argo-watcher/state/postgres_state.go
cmd/argo-watcher/state/postgres_state_test.go
cmd/argo-watcher/state/state_models/task_model.go
db/migrations/000001_init.up.sql
db/migrations/000002_status_reason.up.sql
db/migrations/000003_orm_migration.up.sql
docker-compose.yml
go.mod
go.sum

Returned the migration library that we used in previous iterations. 
Created a new migration that adjusts the table structure to match ORM model configurations.
In future releases we should migrate to a migration tool that supports gorm - Atlas

fix(state): change migrations back to migration library

---

.gitignore
cmd/argo-watcher/argo_api.go
cmd/argo-watcher/argo_api_test.go
cmd/argo-watcher/config/config.go
cmd/argo-watcher/config/config_test.go
go.mod
go.sum

Replace unmaintained `kelseyhightower/envconfig` with maintained `caarlos0/env`, and move some logic to `envConfig.Parse`.

chore(config): replace unmaintained envconfig

---

internal/models/argo.go
internal/models/argo_test.go

fix: managed images annotation whitespace handling (#186)

---

Makefile
cmd/argo-watcher/argo_status_updater.go

Increase retry attempts and change retry delay type

chore(updater): change retry.DelayType to exponential

---

docs/development.md
web/src/Components/TasksTable.js
web/src/Utils.js

Fix for issue #187 + a minor improvement into how we display relative time

fix(ui): task duration

---

cmd/argo-watcher/config/config.go
cmd/argo-watcher/config/config_test.go
cmd/argo-watcher/router.go
pkg/client/client.go
pkg/client/client_test.go
pkg/client/config.go
pkg/client/config_test.go
pkg/client/utility.go
pkg/client/utility_test.go

This PR contains the following changes:
- The server now has a separate endpoint for returning it's configuration (excluding sensitive fields). It is needed for new client functionality (closes #216). In the future, for separate pages in UI.
- The server has a new variable `ARGO_URL_ALIAS` that will be used to generate Application URL in case of in-cluster ArgoCD endpoint.
- The client will now print out a link to the relevant Application to simplify deployment issues troubleshooting.
- The client configuration was migrated to the standard configuration approach in the project.
- Minor code cleanup.

chore: client adjustments

---

web/package-lock.json
web/package.json
web/src/Components/HistoryTasks.js
web/src/Components/Navbar.js
web/src/Components/RecentTasks.js
web/src/Components/Sidebar.js

Adds a simple sidebar with `argo-watcher` configuration details. The sensitive values are excluded on the backend side.
The sidebar is reachable by clicking on `argo-watcher` logo.

chore(ui): add sidebar panel

---

cmd/argo-watcher/config/config.go
cmd/argo-watcher/config/config_test.go

Change `ArgoTimeout` (ARGO_TIMEOUT) to `DeploymentTimeout` (DEPLOYMENT_TIMEOUT) to avoid confusion in the variable purpose.

chore: rename ArgoTimeout to DeploymentTimeout

---

.goreleaser.yaml
Makefile
cmd/argo-watcher/auth/auth.go
cmd/argo-watcher/auth/auth_test.go
cmd/argo-watcher/auth/keycloak.go
cmd/argo-watcher/auth/keycloak_test.go
cmd/argo-watcher/server/router.go
cmd/argo-watcher/server/server.go
go.mod
web/src/Components/TaskView.js
web/src/auth.js

This PR removes the necessity to provide deploy tokens in the front end.
Now, we only prompt the user for basic confirmation:
Additionally, the "ROLLBACK TO THIS VERSION" button is no longer active while the task status is "in progress":

feat(keycloak): simplify redeploy logic

---

web/src/Components/TaskView.js

This PR removes the necessity to refresh the task details page manually.
The task status refresh happens in the background as long as the status is "in progress"

chore(frontend): refresh task status in TaskView.js

---

cmd/argo-watcher/argocd/argo_status_updater.go
cmd/argo-watcher/argocd/argo_status_updater_test.go
cmd/argo-watcher/config/config.go
cmd/argo-watcher/server/server.go
internal/models/argo.go
internal/models/argo_test.go

Adds support for Rollout kind in Application. Basically, it just accepts "Suspended" alongside "Healthy" value.
Closes #248

feat: add support for Rollout kind in Application

---

docs/git-integration.md
internal/models/argo.go
internal/models/gitops.go
internal/models/gitops_test.go
internal/models/updater.go
pkg/updater/interfaces.go
pkg/updater/updater.go
pkg/updater/updater_test.go

When merged, it will close #224

feat(updater): add support for multi source applications

---

cmd/argo-watcher/argocd/argo_status_updater.go
cmd/argo-watcher/argocd/argo_status_updater_test.go
cmd/argo-watcher/config/config.go
cmd/argo-watcher/notifications/webhook.go
cmd/argo-watcher/notifications/webhook_test.go
cmd/argo-watcher/server/server.go

Closes #256, potentially can partly cover #131

feat: add support for sending webhook events

---

.github/workflows/release.yaml
docker-compose.yml
web/src/App.js
web/src/Components/HistoryTasks.js
web/src/Components/Sidebar.js
web/src/Components/TasksTable.js
web/src/deployLockHandler.js

These changes make switch in sidebar reflect the actual state of deploy lock, and it allows to use one ws connection across all components.

chore(frontend): reusable websocket

---

docs/git-integration.md
docs/installation.md
internal/models/argo.go
pkg/updater/config.go
pkg/updater/config_test.go
pkg/updater/updater.go
pkg/updater/updater_test.go

feat(updater): commit message template

---

cmd/argo-watcher/argocd/argo.go
cmd/argo-watcher/server/router.go
cmd/argo-watcher/state/in_memory_state.go
cmd/argo-watcher/state/in_memory_state_test.go
cmd/argo-watcher/state/postgres_state.go
cmd/argo-watcher/state/postgres_state_test.go
cmd/argo-watcher/state/state.go
web/src/Components/ApplicationsFilter.js
web/src/Components/HistoryTasks.js
web/src/Components/RecentTasks.js
web/src/Components/TasksTable.js
web/src/Services/Data.js

chore(frontend): return app list based on timeframe

---

web/src/Components/HistoryTasks.js
web/src/Components/RecentTasks.js

The changes in this PR are the following:
- We no longer add empty variable in search query
- Refresh interval is no longer depending on query, it's saved in local storage

chore(frontend): search parameters adjustments

---

cmd/argo-watcher/server/lockdown.go
cmd/argo-watcher/server/lockdown_test.go

Currently, in scenarios like Sun 10:00 - Sun 10:30, the lockdown is not released on Sun at all. These changes fix it.

fix(lockdown): release logic if start day == end day

---

.goreleaser.yaml

Adds support for filtering commits based on commit type

chore(goreleaser): adjust generated changelog

---

pkg/client/client.go
pkg/client/client_test.go
pkg/client/config.go
pkg/client/utility.go
pkg/client/utility_test.go

These changes support specifying retry interval and expected deployment time to provide feedback about a potential deployment issue sooner.
After the threshold is met, the client will start logging additional information about the necessity of checking the setup in ArgoCD UI.

chore(client): add support for additional configuration

---

cmd/argo-watcher/argocd/argo_status_updater.go
docs/git-integration.md
internal/models/argo.go
internal/models/argo_test.go

Closes #308 by implementing `argo-watcher/fire-and-forget` annotation.

feat(updater): add fire and forget mode

---

web/package-lock.json
web/package.json
web/tsconfig.json

fixes constant token refresh on recent keycloak version

chore: bump keycloak-js to 26.0.5

---

.gitignore
cmd/argo-watcher/auth/auth.go
cmd/argo-watcher/auth/auth_test.go
cmd/argo-watcher/auth/jwt.go
cmd/argo-watcher/auth/jwt_test.go
docs/git-integration.md
mkdocs.yml

Now, we are validating whether the token has expired and enforcing expiration to be set. The documentation was also adjusted to simplify the bootstrap.
This `will` break backward compatibility with tokens accepted before if they miss mandatory fields.
Related to #288

fix!: jwt validation

---

docker-compose.yml
web/package-lock.json
web/package.json
web/src/Components/HistoryTasks.tsx

This PR adds support for exporting historical tasks to JSON, CSV, or XLSX formats, with anonymization support.

feat(web): add support for historical tasks export

---

cmd/argo-watcher/argocd/argo_status_updater.go
cmd/argo-watcher/argocd/argo_status_updater_test.go
cmd/argo-watcher/config/config.go
cmd/argo-watcher/notifications/webhook.go
cmd/argo-watcher/notifications/webhook_test.go
cmd/argo-watcher/server/server.go

The previous implementation of `WebhookService` had critical design flaws that made it difficult to test and maintain.
The primary issues were:
- **Tight Coupling:** The service directly instantiated a concrete `*http.Client`, making it impossible to unit test the `SendWebhook` logic without making live, external HTTP calls.
- **Brittle Configuration:** The `Content-Type` header was hardcoded to `application/json`, while the payload was generated from a configurable template. This created a high risk of mismatch if the template format were ever changed, leading to difficult-to-diagnose bugs.
This commit refactors the service to address these issues by applying dependency injection and making the configuration more explicit.
Changes:
- An `HTTPClient` interface is introduced to abstract …

refactor(notifications): Make WebhookService testable and robust
