shini4i/argo-watcher

watcher/argo.py
Add missed except for AppDoesNotExistException and set the correct task status
=> fix: handle AppDoesNotExistException

cli/Dockerfile, cli/README.md, cli/cli.py, cli/requirements.txt
Add an example script that can be used from pipeline side to communicate with argo-watcher
=> feat: add a simple cli script

watcher/models.py, watcher/web.py, web/package-lock.json, web/package.json, web/public/index.html, web/src/App.js, web/src/ErrorSnackbar.js, web/src/Navbar.js, web/src/Utils.js, web/src/index.js
Created basic layout and UI for currently executed tasks
=> Create UI for current tasks

watcher/argo.py, watcher/settings.py, watcher/state.py, watcher/web.py
- Add task expiration
- Rename State to InMemoryState as the first step for different state options
=> feat: add task expiration

.github/workflows/build-and-publish-release.yml, .github/workflows/build-and-publish.yml, Dockerfile, README.md, watcher/web.py
- Add conditional static file import for local development support
- Minor cosmetic improvements
- Add workflow for semver version release (tag)
=> fix: fastapi adjustments for local development

README.md, db/migrations/20220325160147_add_project.sql, docker-compose.yaml, watcher/models.py, watcher/state.py, web/src/App.js
=> feat: add project column

.gitignore, Makefile, poetry.lock, pyproject.toml, tests/test_in_memory_state.py, tests/test_web.py, watcher/state.py
- added simple tests
- changed in-memory state expiration approach
=> feat(tests): add basic pytest setup

web/src/App.js
Features implemented
1. Sorting of columns
2. Auto-Refresh
=> feat: add ui sorting and auto-refresh

CHANGELOG.md, tests/test_db_state.py, tests/test_in_memory_state.py, tests/test_web.py, watcher/argo.py, watcher/state.py, watcher/web.py, web/src/Services/Data.js
Added:
- Request parameter to_timestamp
Changed:
- Renamed timestamp to from_timestamp
- Timestamps no longer converted to int for better precision
=> feat: add support for more precise results filtering

CHANGELOG.md, tests/test_in_memory_state.py, watcher/state.py
=> fix: InMemoryState get_state time_range_to

Dockerfile, Dockerfile.client, Dockerfile.mock, cmd/argo-watcher/argo.go, cmd/argo-watcher/main.go, cmd/argo-watcher/state/postgres_state.go, cmd/mock/main.go, docker-compose.yaml
Additionally, add compression to build argo-watcher binary
=> feat: add a simple mock service for easier local development

cmd/argo-watcher/argo.go, cmd/argo-watcher/state/in_memory_state.go, cmd/argo-watcher/state/postgres_state.go
=> chore: minor adjustments

CHANGELOG.md, cmd/argo-watcher/argo.go, cmd/argo-watcher/state/in_memory_state.go
Closes #86 and adds minor improvements
=> fix: e is null

CHANGELOG.md, cmd/argo-watcher/argo.go, cmd/argo-watcher/state/in_memory_state.go, cmd/argo-watcher/state/postgres_state.go, cmd/argo-watcher/state/state.go, go.mod, go.sum
- Tasks with a status "app not found" are removed after one hour as they provide no value in history
- Tasks with a status "in progress" are marked as "aborted" after one hour since that's an indicator of argo-watcher crash
=> feat: add state cleanup support

CHANGELOG.md, web/src/App.js, web/src/Components/HistoryTasks.js, web/src/Components/Navbar.js, web/src/Components/RecentTasks.js, web/src/Components/TasksTable.js
- date and time now is showing in UTC
- changed primary color for the theme
- added pagination to the pages
- other minor improvements
=> feat: UI improvements

web/src/Components/HistoryTasks.js, web/src/Components/Navbar.js, web/src/Components/RecentTasks.js, web/src/Components/TasksTable.js, web/src/Layout.js, web/src/index.css
=> chore: make argo-watcher UI usable on mobile

CHANGELOG.md, cmd/argo-watcher/argo.go, cmd/argo-watcher/argo_test.go, cmd/argo-watcher/main.go
=> chore: switch username + password with token

README.md
=> docs(readme): add workflow diagram and link to article

internal/helpers/helpers.go, internal/helpers/helpers_test.go
New function plus tests for all helper functions
=> feat(helpers): ImageContains helper function

CHANGELOG.md, web/src/Components/TaskView.js, web/src/Components/TasksTable.js
Reworked formatDateTime function to not break whatever the date format or range. 
Reported error - RangeError: Invalid time value
\+ updated changlog with latest changes
=> fix: task view date-time breaks the page

cmd/argo-watcher/state/postgres_state.go, cmd/argo-watcher/state/postgres_state_test.go
=> fix: ui task details with postgres state

cmd/argo-watcher/argo_api_test.go, cmd/argo-watcher/server.go, cmd/argo-watcher/server_test.go, cmd/argo-watcher/state/in_memory_state.go, cmd/argo-watcher/state/in_memory_state_test.go, cmd/argo-watcher/state/postgres_state.go, cmd/argo-watcher/state/postgres_state_test.go, cmd/argo-watcher/state/state.go
Increase test coverage in `state` package and add test for logs init.
=> chore: increase test coverage pt.2

.codecov.yml, .gitignore, Makefile, go.sum, internal/models/argo.go, pkg/updater/interfaces.go, pkg/updater/updater.go, pkg/updater/updater_test.go
Initial work towards goal stated in #178
=> chore(updater): increase test coverage

.pre-commit-config.yaml, cmd/argo-watcher/argo_status_updater_test.go, cmd/argo-watcher/config/config.go, cmd/argo-watcher/main_test.go, cmd/argo-watcher/state/state_test.go, internal/helpers/helpers_test.go, internal/models/argo.go, pkg/updater/updater.go, pkg/updater/updater_test.go
Add an additional pre-commit hook to improve imports sorting
=> chore(pre-commit): add go-imports

Dockerfile, cmd/argo-watcher/argo_status_updater.go, cmd/argo-watcher/state/postgres_state.go, cmd/argo-watcher/state/postgres_state_test.go, cmd/argo-watcher/state/state.go
Minor cleanup + return missed migrations files copy in Dockerfile
=> chore(state): postgres state improvements

.gitignore, .readthedocs.yml, LICENSE, README.md, docs/development.md, docs/git-integration.md, docs/index.md, docs/installation.md, mkdocs.yml
=> feat: add initial readthedocs setup

web/src/Components/Navbar.js
=> feat(ui): add docs button

pkg/client/client.go, pkg/client/client_test.go, pkg/client/utility.go, pkg/client/utility_test.go
Improve logging, and increase test coverage
=> chore: minor client changes

.gitignore, cmd/argo-watcher/config/config_test.go, cmd/argo-watcher/metrics_test.go, cmd/argo-watcher/router_test.go
This is a small step towards the goal stated in #178
=> chore: increase test coverage

.gitignore, docs/requirements.txt, mkdocs.yml
The following changes were made:
- Added link to github repository in the topbar
- Enabled search suggestions
- Enabled snippets copy button
- Added page authors
=> docs(mkdocs): style improvements
